{
  "errors": [
    {
      "id": 1,
      "name": "Error",
      "message": "this is a general error",
      "stack": "Error: this is a general error\n   at AppComponent.prototype.simulateError1 (http://localhost:8080/bundles/app.66389232b205dfa6d265.bundle.js:41636:9)\n   at Anonymous function (Function code:66:15)\n   at handleEvent (http://localhost:8080/bundles/vendor.66389232b205dfa6d265.bundle.js:14674:87)\n   at callWithDebugContext (http://localhost:8080/bundles/vendor.66389232b205dfa6d265.bundle.js:16183:9)\n   at debugHandleEvent (http://localhost:8080/bundles/vendor.66389232b205dfa6d265.bundle.js:15770:5)\n   at dispatchEvent (http://localhost:8080/bundles/vendor.66389232b205dfa6d265.bundle.js:11086:9)\n   at Anonymous function (http://localhost:8080/bundles/vendor.66389232b205dfa6d265.bundle.js:11711:31)\n   at Anonymous function (http://localhost:8080/bundles/vendor.66389232b205dfa6d265.bundle.js:31679:9)\n   at ZoneDelegate.prototype.invokeTask (http://localhost:8080/bundles/polyfills.66389232b205dfa6d265.bundle.js:13233:13)\n   at onInvokeTask (http://localhost:8080/bundles/vendor.66389232b205dfa6d265.bundle.js:5866:17)",
      "headers": "",
      "createdOn": "2018-01-24T19:57:40.417Z"
    },
    {
      "id": 2,
      "name": "HttpErrorResponse",
      "message": "Http failure response for (unknown url): 0 Unknown Error",
      "status": 0,
      "statusText": "Unknown Error",
      "url": null,
      "headers": "",
      "createdOn": "2018-01-24T19:57:56.582Z"
    }
  ]
}